"""Fix refresh_token field length

Revision ID: 4d052f489a02
Revises: 92321bcbf312
Create Date: 2025-07-26 15:55:50.801378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d052f489a02'
down_revision: Union[str, Sequence[str], None] = '92321bcbf312'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_audit_logs_action'), table_name='auth_audit_logs')
    op.drop_index(op.f('idx_audit_logs_created_at'), table_name='auth_audit_logs')
    op.drop_index(op.f('idx_audit_logs_result'), table_name='auth_audit_logs')
    op.drop_index(op.f('idx_audit_logs_user_id'), table_name='auth_audit_logs')
    op.drop_index(op.f('idx_reset_tokens_expires'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('idx_sessions_expires'), table_name='user_sessions')
    op.drop_index(op.f('idx_sessions_last_accessed'), table_name='user_sessions')
    op.drop_index(op.f('idx_sessions_token'), table_name='user_sessions')
    op.drop_index(op.f('idx_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('idx_users_created_at'), table_name='users')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_oauth'), table_name='users')
    op.drop_index(op.f('idx_users_role_id'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_index(op.f('idx_users_oauth'), 'users', ['oauth_provider', 'oauth_provider_id'], unique=False)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('idx_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('idx_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    op.create_index(op.f('idx_sessions_token'), 'user_sessions', ['session_token'], unique=False)
    op.create_index(op.f('idx_sessions_last_accessed'), 'user_sessions', ['last_accessed_at'], unique=False)
    op.create_index(op.f('idx_sessions_expires'), 'user_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('idx_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('idx_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=False)
    op.create_index(op.f('idx_reset_tokens_expires'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_user_id'), 'auth_audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_logs_result'), 'auth_audit_logs', ['result'], unique=False)
    op.create_index(op.f('idx_audit_logs_created_at'), 'auth_audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('idx_audit_logs_action'), 'auth_audit_logs', ['action'], unique=False)
    # ### end Alembic commands ###
